spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost:3306/testdb;
    user: sa
    password:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: changeme
  # Session
  session:
    store-type: redis
    redis:
      flush-mode: on_save

h2:
  console:


jpa:
  properties:
    hibernate:
      format_sql: true
  show-sql: true
